// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFDOfqp1RlPvEkaYXAPtX72PlGy5tCd1w',
    appId: '1:702885129367:web:797aca820095d1e523cdd2',
    messagingSenderId: '702885129367',
    projectId: 'omniguardian-79658',
    authDomain: 'omniguardian-79658.firebaseapp.com',
    storageBucket: 'omniguardian-79658.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbOybtQ0ouGNgIDCsjh1EMiAHEH8nP6co',
    appId: '1:702885129367:android:0102c6e5e578739723cdd2',
    messagingSenderId: '702885129367',
    projectId: 'omniguardian-79658',
    storageBucket: 'omniguardian-79658.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFDOfqp1RlPvEkaYXAPtX72PlGy5tCd1w',
    appId: '1:702885129367:web:61b596a705a5db5c23cdd2',
    messagingSenderId: '702885129367',
    projectId: 'omniguardian-79658',
    authDomain: 'omniguardian-79658.firebaseapp.com',
    storageBucket: 'omniguardian-79658.appspot.com',
  );

}